name: vuet_flutter
description: Vuet Task Management App - Flutter/Supabase version
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Supabase
  supabase_flutter: ^1.10.25
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Routing
  go_router: ^12.1.3
  
  # Models & Serialization
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  
  # UI Components
  flutter_screenutil: ^5.9.0
  reactive_forms: ^16.1.1
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.1
  
  # Media & Files
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  
  # Calendar & Date/Time
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  
  # Notifications
  flutter_local_notifications: ^16.1.0

  # Environment & Error tracking
  flutter_dotenv: ^5.0.2            # Load .env at runtime
  sentry_flutter: ^7.16.0           # Crash/trace reporting
  flutter_easyloading: ^3.0.5       # Toast / loading HUD

  # Fonts & UI polish
  google_fonts: ^6.1.0              # Match RN typography
  # Firebase dependencies temporarily removed to unblock Web build.
  # firebase_core: ^2.24.2
  # firebase_messaging: ^14.7.10
  
  # Utils
  url_launcher: ^6.2.2
  uuid: ^4.2.2
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  
  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  
  # Phone number handling (for auth)
  phone_number: ^2.0.1
  libphonenumber_plugin: ^0.3.3

  # Flutter SDK localisations
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  go_router_builder: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  mockito: ^5.4.3
  
flutter:
  uses-material-design: true
  
  # Asset and font references removed temporarily for a minimal build.
